enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YT Music 2958]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "both"
version = "6.29.58"
included-patches = "'Disable overlay filter' 'Enable color match player' 'Enable old player background' 'Enable old player layout' 'Enable zen mode' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"

[YT Music 2958 root]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "module"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "both"
version = "6.29.58"
included-patches = "'Disable overlay filter' 'Enable color match player' 'Enable old player background' 'Enable old player layout' 'Enable zen mode' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom package name' 'MicroG support'"

[YT Music 4159]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "arm64-v8a"
version = "6.41.59"
included-patches = "'Disable overlay filter' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"

[YT Music 4159 root]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "module"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "arm64-v8a"
version = "6.41.59"
included-patches = "'Disable overlay filter' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom package name' 'MicroG support'"

[YT Music 4454 ]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "both"
version = "6.44.54"
included-patches = "'Disable overlay filter' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Enable old style miniplayer'"

[YT Music 4454 root]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "module"
patches-source = "YT-Advanced/rex-patches"
integrations-source = "YT-Advanced/rex-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "both"
version = "6.44.54"
included-patches = "'Disable overlay filter' 'Hide double tap overlay filter' 'Replace cast button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom package name' 'Enable old style miniplayer' 'MicroG support'"
